baseURL = "https://hill68.github.io/"
languageCode = "zh-cn"
title = "FlitSoft Docs"
theme = "hugo-theme-relearn"

# 指定 Hugo build 输出到 docs/ 目录
publishDir = "docs"
disableKinds = ["taxonomy"] # 关闭 /tags/ 和 /categories/ 等分类页面

# --- Google Analytics 核心配置 ---

# 1. 启用 GA 服务并提供 ID
[services]
  [services.googleAnalytics]
    ID = "G-TXZZJN3Q2Y"

# 2. 确保隐私设置允许 GA 运行
[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false # 如果设为true，当用户浏览器开启“Do Not Track”时，GA脚本不会加载


# Relearn 主题及其他参数
[params]
  subtitle = "副标题 / 口号"
  dateFormat = "2006-01-02"
  showReadingTime = true
  themeVariant = ['zen-light', 'zen-dark']
 # highlightTheme = "monokai" # 代码块（Code Block）的高亮显示风格为 “Monokai” 
 # highlightTheme = "github"  # 代码块（Code Block）的高亮显示风格为 “github” 
  highlightTheme = "dracula"
  math = true # 若需数学公式支持，启用 MathJax
  disableLandingPageButton = true
  disablePrintButton = false  #显示打印按钮
  customCSS = ["css/custom.css"] #改变页面字体
  
  # 作者信息已合并到 [params] 内部，这是标准做法
  [params.author]
    name = "Z.Huang@FlitSoft"

# Markdown 渲染器配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 允许在 Markdown 中渲染原生 HTML
      unsafe = true
  
    # 启用 passthrough 扩展，并自定义数学分隔符
    [markup.goldmark.extensions]
      # 允许在 Markdown 中渲染原生 HTML
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ['\[', '\]'],
            ['$$', '$$']
          ]
          inline = [
            ['\(', '\)'],
            ['$', '$']
          ]