baseURL = "https://hill68.github.io/"
languageCode = "zh-cn"
title = "FlitSoft Docs"
theme = "hugo-theme-relearn"

# 指定 Hugo build 输出到 docs/ 目录
publishDir = "docs"
disableKinds = ["taxonomy"] # 关闭 /tags/ 和 /categories/ 等分类页面


# 添加高亮配置
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true  # 重要：设置为 true
    style = "dracula"  # 设置高亮主题
    tabWidth = 4


# Relearn 主题及其他参数
# 这是 [params] 表格，里面只应该有 key = value 格式的行
[params]
  subtitle = "SubFlitSoft"
  dateFormat = "2006-01-02"
  showReadingTime = true
  themeVariant = ['zen-light', 'zen-dark']
 # highlightTheme = "dracula"
  math = true
  disableLandingPageButton = true
  disablePrintButton = false
  customCSS = ["css/custom.css"]



# 这是 [markup] 表格，它也是一个独立的块，与上面的都平级
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 允许在 Markdown 中渲染原生 HTML
      unsafe = true

    # 启用 passthrough 扩展，并自定义数学分隔符
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ['\[', '\]'],
            ['$$', '$$']
          ]
          inline = [
            ['\(', '\)'],
            ['$', '$']
          ]

