name: Build & Deploy to GitHub Pages

# 给这个 workflow 写权限
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.3'

      - name: Clean output dir
        run: rm -rf docs

      - name: Build site
        run: |
          hugo --config hugo.toml \
            --minify \
            --cleanDestinationDir \
            --destination docs

      - name: Commit & Push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "ci: rebuild site" || echo "No changes to commit"
          git push
